### ISSUE TITLE
Npm run dev

### ISSUE THREAD

**Issue by Whymess** [UseFedora/frontend-takehome-parcel#2]
I cloned the project. I did NPM I and NPM run dev. This error occurs in the terminal. Is this expected behavior? 
`
> frontend-takehome-parcel@0.0.0 dev /Users/yonimessing/Desktop/frontend-takehome-parcel
> concurrently './node_modules/.bin/parcel ./index.html' 'node ./server'

[1] internal/modules/cjs/loader.js:605
[1]     throw err;
[1]     ^
[1] 
[1] Error: Cannot find module 'request'
[1]     at Function.Module._resolveFilename (internal/modules/cjs/loader.js:603:15)
[1]     at Function.Module._load (internal/modules/cjs/loader.js:529:25)
[1]     at Module.require (internal/modules/cjs/loader.js:658:17)
[1]     at require (internal/modules/cjs/helpers.js:22:18)
[1]     at Object.<anonymous> (/Users/yonimessing/Desktop/frontend-takehome-parcel/server.js:1:79)
[1]     at Module._compile (internal/modules/cjs/loader.js:722:30)
[1]     at Object.Module._extensions..js (internal/modules/cjs/loader.js:733:10)
[1]     at Module.load (internal/modules/cjs/loader.js:620:32)
[1]     at tryModuleLoad (internal/modules/cjs/loader.js:560:12)
[1]     at Function.Module._load (internal/modules/cjs/loader.js:552:3)
[1] node ./server exited with code 1
[0] Server running at http://localhost:1234 
✨  Built in 698ms.
`

**Comment by Whymess** [comment]
It can be solved by doing a simple 
npm install request --save
